version: '3'
services:
  battle_simulation_api:
      build:
        context: ./
        dockerfile: ./images/php-apache/Dockerfile
      ports:
      - "8080:80"
      environment:
          - APP_ENV=development
          - WEB_DOCUMENT_INDEX=public/index.php